### ISSUE TITLE
Most signals disapeared from status REST API call

### ISSUE THREAD

**Issue by solsticedhiver** [xee-lab/xee-api-docs#25]
the following signals have disappeared from a  call to the REST API at https://cloud.xee.com/v3/{car_id}/status, namely
- HighBeamsSts
- LowBeamsSts
- HeadLightsSts
- FrontFogLightSts
- RearFogLightSts
- IntermittentWiperSts
- LowSpeedWiperSts
- ManualWiperSts
- HighSpeedWiperSts
- AutoRearWiperSts
- ManualRearWiperSts

**Comment by quentin7b** [comment]
Were these signals available for the same `car_id` before ?

**Comment by solsticedhiver** [comment]
You are right. I switched from **sandbox** to **cloud**.
That must have ben why.
Sorry for the noise.

**Comment by quentin7b** [comment]
No problem! Feel Free :)
