### ISSUE TITLE
Small typo in xee-api-docs/api/api/v3/README.md

### ISSUE THREAD

**Issue by halfpastfive** [xee-lab/xee-api-docs#26]
In file : xee-api-docs/api/api/v3/README.md

The sentence : 
`Somethings it was v1, sometimes v2` 
should probably be 
`Sometimes it was v1, sometimes v2`

I can fix and do a PR  if you wish. 

Ben-

**Comment by quentin7b** [comment]
A PR would be nice 👍

**Comment by quentin7b** [comment]
Don't know why it's not closed as the [PR has been merged](https://github.com/xee-lab/xee-api-docs/pull/27)
