### ISSUE TITLE
[Trip] Payload : Missing creationDate and lastUpdateDate

### ISSUE THREAD

**Issue by quentin7b** [xee-lab/xee-api-docs#34]
In the [`trips`](https://github.com/xee-lab/xee-api-docs/blob/master/api/api/v3/cars/trips.md) and [`trip`](https://github.com/xee-lab/xee-api-docs/blob/master/api/api/v3/trips/trip_id.md) APIs.

The documentation specifies that the `creationDate` and the `lastUpdateDate` are provided but none of them are in the API.

Solution: Update the API to add the missing values

**Comment by quentin7b** [comment]
@alexjomin added to the conversation be notified of the bug.

**Comment by alexjomin** [comment]
Fixed with PR #54
