### ISSUE TITLE
Advanced signals doc frequency

### ISSUE THREAD

**Issue by tikismoke** [xee-lab/xee-api-docs#42]
Frequency is not describe for advanced signals in doc here: https://dev.xee.com/signals

It could be usefull for somes Dev.

**Comment by quentin7b** [comment]
Yeah,

In fact, by default, advanced signals are not uploaded to the cloud, that's why there is no frequency  :) 

They are available to inform about the possibility to have them for business :)

**Comment by tikismoke** [comment]
Crap no business model for my gpl plugin for gpl apps :(

Le 12 septembre 2016 20:03:48 GMT+02:00, Quentin Klein <notifications@github.com> a écrit :
>Yeah,
>
>In fact, by default, advanced signals are not uploaded to the cloud,
>that's why there is no frequency  :) 
>
>They are available to inform about the possibility to have them for
>business :) 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/xee-lab/xee-api-docs/issues/42#issuecomment-246436423

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
