### ISSUE TITLE
[Signals] Typo in list of signals

### ISSUE THREAD

**Issue by quentin7b** [xee-lab/xee-api-docs#43]
In the list of signals, there are some typos:

* `HighBeamsSts` instead of `HighBeamSts`
* `LowBeamsSts` instead of `LowBeamSts`
* `HeadLightsSts` instead of `HeadLightSts`

**Comment by quentin7b** [comment]
I'll add all the signals for the platform, even **those** which are [not available by default.](https://dev.xee.com/signals)

**Comment by quentin7b** [comment]
See #44

**Comment by LeGuit** [comment]
Au final, il y a un 's' ou pas de 's' ? @quentin7b

**Comment by quentin7b** [comment]
The documentation on GitHub is the truth. See https://github.com/xee-lab/xee-api-docs/blob/master/api/api/v3/cars/signals_list.md
