### ISSUE TITLE
[Cars] locations : TimeZone Parsing + More than one month

### ISSUE THREAD

**Issue by LeGuit** [xee-lab/xee-api-docs#45]
When you request location following this model:
`/v3/cars/{carId}/locations?begin=2016-01-01T00:00:00+00:00&end=....`
you get an parsing issue as an answer.
It seems that your parser only accept 2016-01-01T00:00:00Z format for now.

Also i've noticed another issue about overlap on months
`/v3/cars/{carId}/locations?begin=2016-08-31T22:00:00Z&end=2016-09-16T16:24:32Z`
works even if you have parts on august and september. Is it normal ? 
Because if we try with even more then you get the "You can only request one month max per request" issue (I've tried from start of the year to now).

**Comment by alexjomin** [comment]
Hi, thank you for the feedback, 
I could reproduce, I will give a look ASAP to fix this bug and I'll let you know.

**Comment by quentin7b** [comment]
Keep up informed :)

**Comment by josephpage** [comment]
Any updates ?

**Comment by alexjomin** [comment]
Hello, sorry for the delay. I'm running out of times these days. 

Anyway, @LeGuit could you check that the request is correctly URL encoded?

This request works :
`curl -X GET -H "Authorization: Bearer XXXXX" -H "Content-Type: application/json" "https://staging.xee.com/v3/cars/2155/locations?begin=2016-09-20T00:00:00%2B02:00&end=2016-09-30T00:00:00%2B02:00"`

This one, does not:
`curl -X GET -H "Authorization: Bearer XXXXX" -H "Content-Type: application/json" "https://staging.xee.com/v3/cars/2155/locations?begin=2016-09-20T00:00:00+02:00&end=2016-09-30T00:00:00+02:00"`

**Comment by LeGuit** [comment]
Hey @alexjomin !

I've just test both of those requests and yes the first is working and the second does not.

Referring to the documentation the format should be : 
"Format is 2016-04-20T13:37:42Z(+/-HH:mm)"
So it's strange that the second one does not work

**Comment by josephpage** [comment]
So, the correct URL-encoded url should be : 
`https://{env}.xee.com/v3/cars/{carId}/locations?begin=2016%2D09%2D20T00%3A00%3A00%2B02%3A00&end=2016%2D09%2D30T00%3A00%3A00%2B02%3A00`

**Comment by alexjomin** [comment]
`":"` is indeed an unsafe character, it's better to encode it as `%3A`
