### ISSUE TITLE
[Doc] dev.xee.com/doc outdated

### ISSUE THREAD

**Issue by josephpage** [xee-lab/xee-api-docs#46]
For example :
https://dev.xee.com/doc/api/api/v3/cars/signals_list.md
older than
https://github.com/xee-lab/xee-api-docs/blob/master/api/api/v3/cars/signals_list.md

**Comment by quentin7b** [comment]
Yeah, developer space seems outdated. 
I'll have a look on that

**Comment by josephpage** [comment]
Seems up to date now. Thanks.
