### ISSUE TITLE
API v4: minor details in documentation

### ISSUE THREAD

**Issue by solsticedhiver** [xee-lab/xee-api-docs#89]
I just wanted to report minor issues in documentation or feature request/improvements.

 - In the section "**Request and format**", it could be added that for each request should be used the "Authorization" header with the value "Bearer: $ACCESS_TOKEN" where $ACCES_TOKEN has been granted at the previous step in the OAuth authentication. I guess this is implied but best be explicit, no ?

- In the **pagination** section, in the HTTP snippet example, it is a GET that is performed, hence it is not a `Content-Type` header but an `Accept` header. In the 2 examples.

- In the "**Authorization**" section, there is no mention about the **refresh_token**, nor how to use it.

- <del>In the "**Signals**" section, there is no **list** of the available signals. One have to go and get them in  API v3 doc.</del> I guess signals list is bound to each model of car.

- The signals are returned in **inverse chronological order**. Then, if you use a `Range: signals=-15` as header, one does not get that last 15 signals. In fact, one needs to use `Range: signals=0-15`

- `/vehicles/{vehicleId}/status` needs multiple scopes. One have to guess and try:
    - vehicles.signals.read
    - vehicles.locations.read
    - vehicles.accelerometers.read

It could be mentionned.

There is no explanation of what are privacies and nothing about their purposes. At least, a line would be ggod.

Thanks

**Comment by maxcleme** [comment]
We just update our documentation according to your feedback.

Regarding the scopes, it seems that the renderer is not displaying them, even if they are in our [openapi](https://dev.xee.com/v4-openapi/openapi.yaml) specification, we are investaging :)

Many thanks!
